version: "3.3"
services:
  e2ee-chat-server:
    build: .
    restart: always
    privileged: true
    tty: true
    ports:
      - "3000:3000"
      - "8002:8002"
    volumes:
      - "./data/var_lib_lokinet:/var/lib/lokinet"
      - "./data/chat_server:/data"
    environment:
      - PORT=3000
    dns:
      - 127.3.2.1
      - 8.8.8.8
